### PR TITLE
RFC update(Design system): start v2

### PR DESCRIPTION
**Pull request by ACoolmanTelicent**
https://telicent.atlassian.net/browse/TELFE-119

This is part two, see [part one (data catalog frontend)](https://github.com/Telicent-io/telicent-data-catalogue-frontend/pull/2)

# Request for comments

https://github.com/telicent-oss/telicent-ds/assets/153610820/f84e02cc-688f-4bd6-a39e-ef3979a91e24

I want to try and as much alignment as possible (in the time given)

### CODE REVIEW

**Comment by Justinki50** [comment]
See all button shows all of the data sets owned/published by that user not all data sets

**Review by davec504 — DISMISSED** [review]

**Review by VeeKemp — DISMISSED** [review]

**Review by AlecsMissangu — DISMISSED** [review]

**Comment by ACoolmanTelicent** [comment]
@Greg-teli100 Are [these new builds](https://github.com/Telicent-io/telicent-access/actions/runs/9018067861/job/24778451829) testable/unblocking

**Review by dptelicent — APPROVED** [review]

**Comment by ACoolmanTelicent** [comment]
I'll hold off merging unless @AlecsMissangu  tells me. I assume it will be merged/closed as part of [her work](parentEpic = TELFE-1 AND assignee = 621c984f8a4bb60068f093f7)

**Review by dptelicent — APPROVED** [review]

**Review by dptelicent — APPROVED** [review]

**Comment by ACoolmanTelicent** [comment]
Converting to draft as Alecs is picking bits off this for her branch.

I'll hold off closing until Alecs then

**Comment by ACoolmanTelicent** [comment]
This is again the main feature branch for Design System

**Pull request merged**
