### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by ACoolmanTelicent**
# I've not done lots of testing, but curious **what you guys think of the diff to [package.json](https://github.com/telicent-oss/telicent-ds/pull/16/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)** 

I ran `npx depcheck`, resolved the errors, and tested a single storybook.

Once https://github.com/telicent-oss/telicent-ds/pull/14 is merged, I'll move this from DRAFT, and do some proper testing

### CODE REVIEW

**Comment by davec504** [comment]
I can see the reason for getting some like prop-types if we are using typescript; but I wonder about getting rid of storybook libraries and a11y checks. Is this not over zealous?

**Comment by ACoolmanTelicent** [comment]
> I can see the reason for getting some like prop-types if we are using typescript; but I wonder about getting rid of storybook libraries and a11y checks. Is this not over zealous?

These are unused (as indicated by `depcheck`)

**Comment by davec504** [comment]
That's interesting especially with the A11y plugin because I thought that there was a tab in storybook that would run some sort of analysis on your component.

**Comment by ACoolmanTelicent** [comment]
> That's interesting especially with the A11y plugin because I thought that there was a tab in storybook that would run some sort of analysis on your component.

Interesting. Ok I'll test that

**Comment by ACoolmanTelicent** [comment]
The depcheck tool misidentifies used packages as unused.

**Comment by ACoolmanTelicent** [comment]
I'll close this PR. But I'll create a ticket

**Pull request closed without merging**
