### PR TITLE
OH changes

### PR DESCRIPTION
**Pull request by BMPMS-Telicent**
I've added tests and fixed the storybook for the changes I did last week.  The branch I was pushing to on Thursday is no longer there.  I am hoping that someone can take over from here and do whatever needs to be done.

### CODE REVIEW

**Comment by BMPMS-Telicent** [comment]
> @BMPMS-Telicent
> 
> > The branch I was pushing to on Thursday is no longer there
> > It was merged into `main` to unblock @davec504

I'm aware of that @ACoolmanTelicent.  This is the 'complete' task - with testing, comments and storybook working.  I don't know what to do next and I am hoping someone else will take it from here as I'll do this process so rarely I will forget every time and will likely mess it up so best not to be involved.

**Comment by ACoolmanTelicent** [comment]
> I am hoping that someone can take over from here and do whatever needs to be done.

@BMPMS-Telicent Sorry I've lost context on this PR - is this for the floating edges ticket?

**Comment by BMPMS-Telicent** [comment]
> > I am hoping that someone can take over from here and do whatever needs to be done.
> 
> @BMPMS-Telicent Sorry I've lost context on this PR - is this for the floating edges ticket?

It is the OntologyHierarchy ticket - resolving these issues:

https://github.com/Telicent-io/telicent-ds/issues/379
https://github.com/Telicent-io/telicent-ds/issues/376
(Vanessa's one) https://github.com/Telicent-io/telicent-ontology-app/issues/274
https://github.com/Telicent-io/telicent-ontology-app/issues/230

And now also 

https://github.com/Telicent-io/telicent-ds/issues/367

**Comment by ACoolmanTelicent** [comment]
> and do whatever needs to be done

What specifically are you thinking of?

e.g.
Do you mean the task of merging this PR? (e.g. test and merge)?
Or is there known bugs/features?

**Comment by BMPMS-Telicent** [comment]
> > and do whatever needs to be done
> 
> What specifically are you thinking of?
> 
> e.g. Do you mean the task of merging this PR? (e.g. test and merge)? Or is there known bugs/features?

This is the complete task with testing ready to merge which ticks all the tickets I attached. 

The code submitted on Thursday was to test functionality ahead of Bhavi's meeting with Ian - thus the need for a release candidate.

I don't know how to merge/push/etc to OSS repos @ACoolmanTelicent and I'm hoping I don't need to as the only open source item that is my responsibility is this component and it's over my head.  I'd be really grateful if someone could take this on please.  

 I'd be exceed

**Comment by ACoolmanTelicent** [comment]
@BMPMS-Telicent 
> I don't know how to merge/push/etc 
Ah, just merge as normal ([instructions for the future](https://github.com/Telicent-io/docs/blob/main/eng/how-to/oss.md))

And ping me when you need to generate a new build until I fix that process

**Pull request merged**
